### ISSUE TITLE
POST error 500 with "register_and_broadcast_node" route

### ISSUE THREAD

**Issue by 0xrgg** [morris-ribs/BlockchainBetSportPython#1]
Hello,
I have been working through a few blockchain tutorials and found yours especially helpful for creating the network of nodes, however I am facing an issue with the register_and_broadcast_node() function/route.

I copied your code for both the function inside blockchain.py (register_new_node) and register_node, register_and_broadcast_node and register_nodes_bulk into app.py.

Registering nodes on their own does work and will add to the blockchain, however, they do not get broadcast out to the other running nodes. 

The POST requests I have been trying are formatted as
{
   "newnodeurl": "localhost:9001"
}

This is the error that is being returned:
`127.0.0.1 - - [13/Apr/2020 12:55:56] "POST /register-and-broadcast-node HTTP/1.1" 500 -
[2020-04-13 13:01:51,558] ERROR in app: Exception on /register-and-broadcast-node [POST]
Traceback (most recent call last):
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib64/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib64/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 54, in register_and_broadcast_node
    requests.post(network_node+"/register-node", data=payload_to_post)
  File "/usr/lib/python3.7/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 640, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 731, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No connection adapters were found for 'localhost:9001/register-node'
`

**Comment by 0xrgg** [comment]
Nevermind! I figured it out, I wasn't using "http://" prefix - which apparently does matter, mystery solved!
